import React,{useEffect,useMemo,useState}from"react";
import{AlertTriangle,Check,Fuel,Pencil,PiggyBank,Plus,Target,Trash2,TrendingUp,X}from"lucide-react";
import{supabase}from"./lib/supabase";
const brl=v=>Number(v||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});
function simulate(items,s,mode){const months=["Jul","Ago","Set","Out","Nov","Dez"],b=items.map(x=>({...x,left:Math.max(0,x.total_installments-x.current_installment+1)}));let reserve=Number(s.initial_reserve||0);return months.map(month=>{const income=Number(s.tapioca_income||0),fuel=Number(s.monthly_fuel||0),regular=b.reduce((a,x)=>a+(x.left?Number(x.installment_amount):0),0);let cash=Math.max(0,income-fuel-regular),extra=0,saved=0;b.forEach(x=>{if(x.left)x.left--});if(mode==="save"){saved=cash;reserve+=saved;cash=0}else{if(reserve<Number(s.minimum_reserve||0)){saved=Math.min(cash,Number(s.minimum_reserve)-reserve);reserve+=saved;cash-=saved}const order=b.filter(x=>x.left).sort((a,z)=>mode==="payoff"?a.left*a.installment_amount-z.left*z.installment_amount:z.installment_amount-a.installment_amount);for(const x of order){if(cash<=0)break;const units=Math.min(x.left,mode==="payoff"?x.left:1,Math.floor((cash+.001)/x.installment_amount));x.left-=units;cash-=units*x.installment_amount;extra+=units*x.installment_amount}}return{month,income,fuel,regular,extra,saved,reserve,free:cash,remaining:b.reduce((a,x)=>a+x.left*x.installment_amount,0)}})}
export default function ExpenseElimination({owner,notify}){const[items,setItems]=useState([]),[s,setS]=useState({tapioca_income:0,monthly_fuel:0,initial_reserve:0,minimum_reserve:0,delivery_hours_week:0,delivery_net_hour:0,exit_date:null}),[mode,setMode]=useState("payoff"),[edit,setEdit]=useState(null),[loading,setLoading]=useState(true);
async function load(){setLoading(true);const[{data:rows},{data:cfg}]=await Promise.all([supabase.from("expense_plan_items").select("*").eq("owner_id",owner.id).neq("status","deleted").order("created_at"),supabase.from("expense_plan_settings").select("*").eq("owner_id",owner.id).maybeSingle()]);if(cfg)setS(cfg);setItems(rows||[]);setLoading(false)}useEffect(()=>{load()},[owner.id]);
const plan=useMemo(()=>simulate(items,s,mode),[items,s,mode]),total=items.reduce((a,x)=>a+(x.total_installments-x.current_installment+1)*x.installment_amount,0),delivery=Number(s.delivery_hours_week||0)*4.33*Number(s.delivery_net_hour||0),december=plan.at(-1)||{},protectedBalance=Number(december.reserve||0)-Number(december.remaining||0);
async function saveSettings(){const{data,error}=await supabase.from("expense_plan_settings").upsert({...s,owner_id:owner.id,updated_at:new Date().toISOString()},{onConflict:"owner_id"}).select().single();if(error)return notify("Não foi possível salvar o plano.");setS(data);notify("Plano atualizado.")}
async function saveItem(e){e.preventDefault();const f=new FormData(e.currentTarget),row={owner_id:owner.id,name:f.get("name"),creditor:f.get("creditor")||"Cartão",current_installment:+f.get("current"),total_installments:+f.get("total"),installment_amount:+f.get("amount"),updated_at:new Date().toISOString()};const{error}=edit?.id?await supabase.from("expense_plan_items").update(row).eq("id",edit.id).eq("owner_id",owner.id):await supabase.from("expense_plan_items").insert(row);if(error)return notify("Não foi possível salvar a despesa.");setEdit(null);await load();notify("Despesa salva.")}
async function remove(x){if(!confirm(`Excluir ${x.name} deste plano?`))return;await supabase.from("expense_plan_items").update({status:"deleted"}).eq("id",x.id).eq("owner_id",owner.id);load()}
if(loading)return <div className="module-empty">Carregando seu plano…</div>;return <div className="elimination-page"><section className="elimination-hero"><div><small>PLANO DE SAÍDA{s.exit_date?` · ${new Date(s.exit_date+"T12:00").toLocaleDateString("pt-BR",{day:"2-digit",month:"long"})}`:""}</small><h2>Transforme a renda extra em liberdade mensal.</h2><p>Primeiro cartão e combustível. Depois, reserva e eliminação das parcelas.</p></div><div><span>Saldo parcelado</span><strong>{brl(total)}</strong><small>{items.length} despesas ativas</small></div></section><div className="plan-alert"><AlertTriangle/><span><strong>O primeiro mês exige atenção.</strong> As parcelas consomem {brl(plan[0]?.regular)} dos {brl(s.tapioca_income)}. Informe o combustível para ver o saldo real.</span></div>
<section className="elimination-settings"><label>Renda da tapiocaria<input type="number" step=".01" value={s.tapioca_income} onChange={e=>setS(v=>({...v,tapioca_income:e.target.value}))}/></label><label>Combustível mensal<input type="number" step=".01" value={s.monthly_fuel} onChange={e=>setS(v=>({...v,monthly_fuel:e.target.value}))}/></label><label>Reserva mínima<input type="number" step=".01" value={s.minimum_reserve} onChange={e=>setS(v=>({...v,minimum_reserve:e.target.value}))}/></label><button className="primary" onClick={saveSettings}><Check/>Salvar</button></section>
<div className="strategy-switch"><button className={mode==="payoff"?"active":""} onClick={()=>setMode("payoff")}><Target/><span><strong>Modelo Quitação</strong><small>Encerra primeiro os menores saldos.</small></span></button><button className={mode==="advance"?"active":""} onClick={()=>setMode("advance")}><TrendingUp/><span><strong>Modelo Adiantamentos</strong><small>Adianta as maiores mensalidades.</small></span></button><button className={mode==="save"?"active":""} onClick={()=>setMode("save")}><PiggyBank/><span><strong>Guardar até dezembro</strong><small>Paga mês a mês e acumula toda a sobra.</small></span></button></div>
<section className="projection-grid">{plan.map(r=><article key={r.month}><div><strong>{r.month}</strong><span>{brl(r.remaining)} restantes</span></div><p><span>Parcelas</span><b>{brl(r.regular)}</b></p><p><span>{mode==="save"?"Guardado no mês":"Extra"}</span><b className="green">{brl(mode==="save"?r.saved:r.extra)}</b></p><p><span>Reserva acumulada</span><b>{brl(r.reserve)}</b></p><i><b style={{width:`${Math.max(3,100-r.remaining/Math.max(total,1)*100)}%`}}/></i></article>)}</section>
{mode==="save"&&<section className="termination-projection"><div><small>RESCISÃO PROJETADA · DEZEMBRO</small><h3>Seu fundo particular de saída</h3><p>Como não haverá rescisão da tapiocaria, este é o valor formado pelas sobras mensais.</p></div><span><small>Valor guardado</small><strong>{brl(december.reserve)}</strong></span><span><small>Dívidas após dezembro</small><strong className="debt">{brl(december.remaining)}</strong></span><span className="net"><small>Saldo protegido após pagar tudo</small><strong>{brl(protectedBalance)}</strong></span></section>}
<section className="delivery-scenario"><div><Fuel/><span><small>PROJEÇÃO APÓS A TAPIOCARIA</small><h3>Entregas por aplicativo</h3><p>Simulação editável; não é tratada como renda garantida.</p></span></div><label>Horas por semana<input type="number" value={s.delivery_hours_week} onChange={e=>setS(v=>({...v,delivery_hours_week:e.target.value}))}/></label><label>Líquido por hora<input type="number" step=".01" value={s.delivery_net_hour} onChange={e=>setS(v=>({...v,delivery_net_hour:e.target.value}))}/></label><div><small>Estimativa mensal</small><strong>{brl(delivery)}</strong><span>antes de manutenção extraordinária</span></div></section>
<section className="expense-list"><div className="panel-title"><div><h3>Parcelamentos cadastrados</h3><p>Base: julho de 2026.</p></div><button className="primary" onClick={()=>setEdit({})}><Plus/>Adicionar</button></div>{items.map(x=><article key={x.id}><em>{x.logo_url?<img src={x.logo_url} alt={`Logo ${x.name}`} loading="lazy" onError={e=>{e.currentTarget.hidden=true;e.currentTarget.nextElementSibling.hidden=false}}/>:null}<b hidden={Boolean(x.logo_url)}>{x.name[0]}</b></em><div><strong>{x.name}</strong><small>{x.creditor} · {x.current_installment}/{x.total_installments}</small></div><b>{brl(x.installment_amount)}</b><span>{brl((x.total_installments-x.current_installment+1)*x.installment_amount)} restantes</span><button onClick={()=>setEdit(x)}><Pencil/></button><button className="danger" onClick={()=>remove(x)}><Trash2/></button></article>)}</section>
{edit&&<div className="plan-modal-bg"><form className="plan-modal" onSubmit={saveItem}><div><h3>{edit.id?"Editar despesa":"Nova despesa"}</h3><button type="button" onClick={()=>setEdit(null)}><X/></button></div><label>Nome<input name="name" required defaultValue={edit.name}/></label><label>Credor/cartão<input name="creditor" defaultValue={edit.creditor}/></label><section><label>Parcela atual<input name="current" type="number" min="1" required defaultValue={edit.current_installment||1}/></label><label>Total<input name="total" type="number" min="1" required defaultValue={edit.total_installments||1}/></label></section><label>Valor<input name="amount" type="number" step=".01" min=".01" required defaultValue={edit.installment_amount}/></label><button className="primary"><Check/>Salvar despesa</button></form></div>}</div>}
