import React,{useEffect,useMemo,useState} from 'react';
import{createRoot}from'react-dom/client';
import{Home,ArrowLeftRight,CreditCard,UserRound,ArrowDownLeft,CalendarDays,ChartNoAxesCombined,Sparkles,Settings,Search,Bell,Plus,Eye,TrendingUp,TrendingDown,WalletCards,Clock3,AlertTriangle,Wifi,Zap,Building2,ShieldCheck,Check,ChevronRight,Menu,X,MoreHorizontal,Sun,Moon,FileText,Download,Send,Landmark,Play,Target,PackageOpen}from'lucide-react';
import'./styles.css';
import{supabase}from'./lib/supabase';

const money=n=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const nav=[['Início',Home],['Movimentações',ArrowLeftRight],['Cartões',CreditCard],['Me devem',UserRound],['Eu devo',ArrowDownLeft],['Calendário',CalendarDays],['Relatórios',ChartNoAxesCombined],['Criar função',Sparkles],['Configurações',Settings]];
const seedTx=[
 {id:1,name:'Salário Linx',cat:'Salário',date:'05 jul',value:5000,type:'in',status:'Recebido'},
 {id:2,name:'Expresso Tapiocaria',cat:'Renda extra',date:'08 jul',value:1180,type:'in',status:'Recebido'},
 {id:3,name:'Condomínio',cat:'Moradia',date:'10 jul',value:742.8,type:'out',status:'Pago'},
 {id:4,name:'Mercado do mês',cat:'Alimentação',date:'12 jul',value:628.4,type:'out',status:'Pago'},
 {id:5,name:'Revisão Lander',cat:'Transporte',date:'15 jul',value:399.75,type:'out',status:'Pendente'}];
const debts=[
 {name:'Marcelo Silva',desc:'Compra no cartão Inter',value:680,due:'Hoje',tone:'warning',phone:'5511999999999'},
 {name:'Fernanda Costa',desc:'Netflix + Spotify',value:74.9,due:'Amanhã',tone:'orange',phone:'5511988888888'},
 {name:'Ezequiel',desc:'Equipamento da tapiocaria',value:450,due:'Vencido há 2 dias',tone:'danger',phone:'5511977777777'}];
const owed=[
 {name:'Loja do Amigo',desc:'Capacete Lander',total:900,left:600,next:'20 jul · 2/4',tone:'warning'},
 {name:'Banco Inter',desc:'Empréstimo pessoal',total:2400,left:1320,next:'28 jul · 12/24',tone:'orange'},
 {name:'Oficina do Zé',desc:'Manutenção da moto',total:520,left:520,next:'Vencido há 2 dias',tone:'danger'}];

function FinanceApp({owner}){
 const[page,setPage]=useState('Início'),[menu,setMenu]=useState(false),[dark,setDark]=useState(false),[modal,setModal]=useState(null),[toast,setToast]=useState(''),[tx,setTx]=useState([]),[query,setQuery]=useState('');
 const notify=m=>{setToast(m);setTimeout(()=>setToast(''),2600)};
 const filtered=useMemo(()=>tx.filter(x=>(x.name+x.cat).toLowerCase().includes(query.toLowerCase())),[tx,query]);
 useEffect(()=>{(async()=>{const{data,error}=await supabase.from('transactions').select('*').eq('owner_id',owner.id).order('transaction_date',{ascending:false});if(!error)setTx((data||[]).map(x=>({id:x.id,name:x.name,cat:x.category,value:Number(x.amount),date:new Date(x.transaction_date+'T12:00:00').toLocaleDateString('pt-BR',{day:'2-digit',month:'short'}),type:x.transaction_type==='income'?'in':'out',status:{pending:'Pendente',paid:'Pago',received:'Recebido',overdue:'Vencido',cancelled:'Cancelado'}[x.status]})))})()},[owner.id]);
 async function addTx(e){e.preventDefault();const f=new FormData(e.currentTarget);const row={owner_id:owner.id,name:f.get('name'),category:f.get('cat'),amount:Number(f.get('value')),transaction_type:f.get('type')==='in'?'income':'expense',status:'pending'};const{data,error}=await supabase.from('transactions').insert(row).select().single();if(error){notify('Não foi possível salvar. Tente novamente.');return}setTx(v=>[{id:data.id,name:data.name,cat:data.category,value:Number(data.amount),date:'Hoje',type:f.get('type'),status:'Pendente'},...v]);setModal(null);notify('Movimentação salva no Supabase');}
 return <div className={dark?'app dark':'app'}>
  <aside className={menu?'sidebar open':'sidebar'}><div className="brand"><span><WalletCards/></span>Finance Hub</div><button className="close" onClick={()=>setMenu(false)}><X/></button>
   <nav>{nav.map(([n,I])=><button key={n} className={page===n?'active':''} onClick={()=>{setPage(n);setMenu(false)}}><I/><span>{n}</span>{n==='Me devem'&&<b>3</b>}</button>)}</nav>
   <button className="profile"><span>{initials(owner.name)}</span><div><strong>{owner.name}</strong><small>Perfil pessoal</small></div><MoreHorizontal/></button>
  </aside>
  {menu&&<div className="scrim" onClick={()=>setMenu(false)}/>} 
  <main><header><div className="hello"><button className="mobile-menu" onClick={()=>setMenu(true)}><Menu/></button><div><h1>{page==='Início'?`Olá, ${owner.name.split(' ')[0]} 👋`:page}</h1><p>{page==='Início'?'Sua vida financeira em um só lugar.':'Gerencie tudo de forma simples e rápida.'}</p></div></div>
   <div className="head-actions"><label className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar em todo o Finance Hub"/></label><button className="icon" onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button><button className="icon bell"><Bell/><i>3</i></button><button className="primary" onClick={()=>setModal('transaction')}><Plus/>Nova movimentação</button><span className="avatar">{initials(owner.name)}</span></div>
  </header>
  <div className="content">{page==='Início'?<Dashboard setPage={setPage} notify={notify} tx={tx}/>:page==='Movimentações'?<Transactions rows={filtered} open={()=>setModal('transaction')}/>:page==='Me devem'?<ObligationsPage owner={owner} direction="receivable" notify={notify}/>:page==='Eu devo'?<ObligationsPage owner={owner} direction="payable" notify={notify}/>:page==='Cartões'?<CardsModule owner={owner} notify={notify}/>:page==='Calendário'?<CalendarModule tx={tx}/>:page==='Relatórios'?<ReportsModule tx={tx}/>:page==='Criar função'?<FunctionBuilder owner={owner} notify={notify}/>:page==='Configurações'?<SettingsModule owner={owner} dark={dark} setDark={setDark} notify={notify}/>:null}</div>
  </main>
  {modal==='transaction'&&<Modal title="Nova movimentação" close={()=>setModal(null)}><form onSubmit={addTx} className="form"><div className="seg"><label><input type="radio" name="type" value="in" defaultChecked/>Receita</label><label><input type="radio" name="type" value="out"/>Despesa</label></div><label>Descrição<input name="name" required placeholder="Ex.: Venda, mercado, salário"/></label><div className="fields"><label>Categoria<input name="cat" required placeholder="Selecione ou digite"/></label><label>Valor<input name="value" required type="number" min="0" step=".01" placeholder="R$ 0,00"/></label></div><label>Observação<textarea placeholder="Opcional"/></label><button className="primary submit">Salvar movimentação</button></form></Modal>}
  {toast&&<div className="toast"><Check/>{toast}</div>}
 </div>
}

const initials=n=>n.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
function AuthGate(){
 const[loading,setLoading]=useState(true),[user,setUser]=useState(null),[owner,setOwner]=useState(null),[error,setError]=useState('');
 useEffect(()=>{(async()=>{if(!supabase){setError('Configuração do banco não encontrada.');setLoading(false);return}let{data:{session}}=await supabase.auth.getSession();if(!session){const{data,error}=await supabase.auth.signInAnonymously();if(error){setError('Ative Anonymous Sign-Ins no Supabase Authentication.');setLoading(false);return}session=data.session}setUser(session.user);const{data:o}=await supabase.from('owners').select('*').eq('id',session.user.id).maybeSingle();setOwner(o);setLoading(false)})()},[]);
 async function createOwner(e){e.preventDefault();const f=new FormData(e.currentTarget);const row={id:user.id,name:f.get('name').trim(),profile_color:f.get('color')};const{data,error}=await supabase.from('owners').insert(row).select().single();if(error){setError(error.message);return}setOwner(data)}
 if(loading)return <div className="boot"><span><WalletCards/></span><p>Preparando seu Finance Hub…</p></div>;
 if(owner)return <FinanceApp owner={owner}/>;
 return <div className="onboarding"><div className="onboard-brand"><span><WalletCards/></span>Finance Hub</div><div className="onboard-card"><div className="onboard-icon"><Sparkles/></div><h1>Vamos criar seu espaço financeiro</h1><p>Esta identificação vincula todos os dados ao seu perfil. Não precisa de senha.</p>{error&&<div className="form-error">{error}</div>}<form onSubmit={createOwner}><label>Seu nome<input name="name" required minLength="2" placeholder="Ex.: Lucas Alencar" autoFocus/></label><label>Cor do perfil<input name="color" type="color" defaultValue="#6445ed"/></label><button className="primary submit">Entrar no Finance Hub<ChevronRight/></button></form><small>Seus dados ficam protegidos e isolados no Supabase.</small></div></div>
}

function Dashboard({setPage,notify,tx}){const income=tx.filter(x=>x.type==='in').reduce((a,x)=>a+x.value,0),expense=tx.filter(x=>x.type==='out').reduce((a,x)=>a+x.value,0),balance=income-expense;return <>
 <section className="balance-row"><div className="balance"><div><span>Saldo atual <Eye/></span><strong>{money(balance)}</strong><small><TrendingUp/> Dados reais <em>das movimentações cadastradas</em></small></div><WalletCards/></div>
 <div className="stats">{[[TrendingUp,'Entradas',income,`${tx.filter(x=>x.type==='in').length} lançamentos`,'green'],[TrendingDown,'Saídas',expense,`${tx.filter(x=>x.type==='out').length} lançamentos`,'red'],[UserRound,'A receber',0,'Cadastre em Me devem','blue'],[CreditCard,'A pagar',0,'Cadastre em Eu devo','amber']].map(([I,l,v,d,c])=><div className="stat" key={l}><i className={c}><I/></i><span>{l}</span><strong>{money(v)}</strong><small>{d}</small></div>)}</div></section>
 <section className="main-grid"><div className="panel chart"><div className="panel-title"><div><h2>Entradas x Saídas</h2><p><i className="dot violet"/> Entradas <i className="dot teal"/> Saídas</p></div><button>Este mês <ChevronRight/></button></div><BarChart/></div>
 <div className="panel pending"><div className="panel-title"><h2>Pendências importantes</h2><button onClick={()=>setPage('Eu devo')}>Ver todas</button></div><div className="real-empty"><AlertTriangle/><strong>Nenhuma pendência carregada</strong><span>Cadastre suas obrigações em “Eu devo”.</span><button onClick={()=>setPage('Eu devo')}>Cadastrar obrigação</button></div></div></section>
 <section className="lower-grid"><div className="panel payments"><div className="panel-title"><h2>Últimas movimentações</h2><button onClick={()=>setPage('Movimentações')}>Ver todas</button></div>{tx.slice(0,4).map(x=><div className="pay" key={x.id}><i>{x.type==='in'?<TrendingUp/>:<TrendingDown/>}</i><div><strong>{x.name}</strong><span>{x.cat} · {x.date}</span></div><b className={x.type==='in'?'pos':'neg'}>{money(x.value)}</b></div>)}{!tx.length&&<div className="real-empty"><FileText/><strong>Nenhuma movimentação</strong><span>Use “Nova movimentação” para começar.</span></div>}</div>
 <div className="panel categories"><div className="panel-title"><h2>Resumo financeiro</h2><button onClick={()=>setPage('Relatórios')}>Relatório</button></div><div className="cat-body"><div className="donut"><span><small>Saídas</small>{money(expense)}</span></div><ul><li><i style={{background:'#19b9a4'}}/>Receitas<b>{money(income)}</b></li><li><i style={{background:'#ff5e6c'}}/>Despesas<b>{money(expense)}</b></li><li><i style={{background:'#6c4cff'}}/>Saldo<b>{money(balance)}</b></li></ul></div></div></section>
 </>}

function BarChart(){let a=[42,65,52,79,44,60,87,54,73,46,82,64,90,55,71,48,76,58,84,62,69,88,53,80,59,74,49,66,78,57];return <div className="bars"><span className="gridline g1">R$ 4 mil</span><span className="gridline g2">R$ 2 mil</span><span className="gridline g3">R$ 0</span>{a.map((h,i)=><div className="barpair" key={i}><i style={{height:h+'%'}}/><b style={{height:(h*.55+8)+'%'}}/></div>)}<div className="axis"><span>01/jul</span><span>10/jul</span><span>20/jul</span><span>31/jul</span></div></div>}

function Transactions({rows,open}){const[filter,setFilter]=useState('all');const shown=rows.filter(x=>filter==='all'||x.type===filter);return <div className="page-panel"><div className="page-head"><div><h2>Movimentações</h2><p>Acompanhe todas as entradas e saídas.</p></div>{open&&<button className="primary" onClick={open}><Plus/>Adicionar</button>}</div><div className="filters"><button className={filter==='all'?'selected':''} onClick={()=>setFilter('all')}>Todas</button><button className={filter==='in'?'selected':''} onClick={()=>setFilter('in')}>Receitas</button><button className={filter==='out'?'selected':''} onClick={()=>setFilter('out')}>Despesas</button></div><div className="table">{shown.map(r=><div className="tr" key={r.id}><i className={r.type==='in'?'txicon in':'txicon out'}>{r.type==='in'?<TrendingUp/>:<TrendingDown/>}</i><div><strong>{r.name}</strong><span>{r.cat}</span></div><span>{r.date}</span><span>{r.status}</span><b className={r.type==='in'?'pos':'neg'}>{r.type==='in'?'+ ':'- '}{money(r.value)}</b><button aria-label="Mais opções"><MoreHorizontal/></button></div>)}{!shown.length&&<EmptyState text="Nenhuma movimentação neste filtro."/>}</div></div>}
function DebtPage({notify}){return <CardsPage intro="Valores que outras pessoas precisam pagar para você." total="Total a receber" value={3280}><div className="debt-grid">{debts.map(d=><div className="debt-card" key={d.name}><div className="debt-avatar">{d.name[0]}</div><div className="debt-top"><div><h3>{d.name}</h3><p>{d.desc}</p></div><span className={d.tone}>{d.due}</span></div><div className="debt-value"><small>Valor pendente</small><strong>{money(d.value)}</strong></div><div className="card-actions"><button onClick={()=>notify('Recebimento registrado')}><Check/>Receber</button><button className="whatsapp" onClick={()=>window.open(`https://wa.me/${d.phone}?text=${encodeURIComponent(`Olá, ${d.name}! Passando para lembrar do valor de ${money(d.value)} referente a ${d.desc}.`)}`)}><Send/>Cobrar</button></div></div>)}</div></CardsPage>}
function OwedPage({notify}){return <CardsPage intro="Suas compras, empréstimos e compromissos a pagar." total="Total que eu devo" value={2440}><div className="debt-grid">{owed.map(d=><div className="debt-card" key={d.name}><div className="debt-top"><div><h3>{d.name}</h3><p>{d.desc}</p></div><span className={d.tone}>{d.next}</span></div><div className="progress"><i style={{width:(d.left/d.total*100)+'%'}}/></div><div className="debt-value row"><span><small>Valor total</small><b>{money(d.total)}</b></span><span><small>Restante</small><strong>{money(d.left)}</strong></span></div><div className="card-actions"><button onClick={()=>notify('Parcela marcada como paga')}><Check/>Pagar parcela</button><button>Detalhes</button></div></div>)}</div></CardsPage>}
function CardsPage({intro,total,value,children}){return <><div className="summary-hero"><div><h2>{total}</h2><strong>{money(value)}</strong><p>{intro}</p></div><button className="primary"><Plus>Novo</Plus>Novo cadastro</button></div>{children}</>}
function FunctionBuilder({owner,notify}){const[step,setStep]=useState(1),[name,setName]=useState(''),[fields,setFields]=useState(['Cliente','Valor','Data','Status']);async function finish(){const{error}=await supabase.from('custom_modules').insert({owner_id:owner.id,name:name||'Nova função',field_schema:fields.map(x=>({name:x,type:x==='Valor'?'number':'text'}))});if(error)return notify(error.code==='23505'?'Essa função já existe.':'Não foi possível criar a função.');notify(`Função ${name} criada e salva!`);setStep(1);setName('')}return <div className="builder"><div className="builder-copy"><span><Sparkles/> Principal diferencial</span><h2>Crie uma função do seu jeito</h2><p>Monte um módulo profissional para qualquer atividade: entregas, vendas, serviços ou consultoria.</p><ul><li><Check/>Formulário e cadastro automáticos</li><li><Check/>Indicadores e gráficos integrados</li><li><Check/>Alertas, pesquisa e exportação</li></ul></div><div className="builder-form"><div className="steps"><b className={step>=1?'on':''}>1</b><i/><b className={step>=2?'on':''}>2</b><i/><b className={step>=3?'on':''}>3</b></div>{step===1&&<><h3>Qual atividade você quer controlar?</h3><label>Nome da função<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Motoboy"/></label><div className="suggestions">{['Motoboy','Venda de bolos','Freelancer','Consultoria'].map(x=><button key={x} onClick={()=>setName(x)}>{x}</button>)}</div></>}{step===2&&<><h3>Quais informações deseja registrar?</h3>{['Cliente','Valor','Data','Status','Quilometragem'].map(x=><label className="check" key={x}><input type="checkbox" checked={fields.includes(x)} onChange={()=>setFields(v=>v.includes(x)?v.filter(f=>f!==x):[...v,x])}/><span><Check/></span>{x}</label>)}</>}{step===3&&<div className="success"><Sparkles/><h3>Seu módulo está pronto!</h3><p>“{name}” será salvo no Supabase.</p></div>}<button className="primary submit" disabled={step===1&&!name.trim()} onClick={()=>step<3?setStep(step+1):finish()}>{step<3?'Continuar':'Criar função'}<ChevronRight/></button></div></div>}

function ObligationsPage({owner,direction,notify}){const[items,setItems]=useState([]),[open,setOpen]=useState(false);const isRecv=direction==='receivable';async function load(){const{data}=await supabase.from('obligations').select('*').eq('owner_id',owner.id).eq('direction',direction).order('created_at',{ascending:false});setItems(data||[])}useEffect(()=>{load()},[direction]);async function add(e){e.preventDefault();const f=new FormData(e.currentTarget);const amount=Number(f.get('amount'));const{error}=await supabase.from('obligations').insert({owner_id:owner.id,direction,counterparty_name:f.get('name'),phone:f.get('phone')||null,description:f.get('description'),total_amount:amount,remaining_amount:amount,next_due_date:f.get('due')||null});if(error)return notify('Não foi possível salvar.');setOpen(false);load();notify('Obrigação salva no Supabase')}async function settle(x){await supabase.from('obligations').update({status:'paid',remaining_amount:0}).eq('id',x.id).eq('owner_id',owner.id);load();notify(isRecv?'Recebimento confirmado':'Pagamento confirmado')}const total=items.reduce((a,x)=>a+Number(x.remaining_amount),0);return <><div className="summary-hero"><div><h2>{isRecv?'Total a receber':'Total que eu devo'}</h2><strong>{money(total)}</strong><p>{items.length} registro(s) em seu banco.</p></div><button className="primary" onClick={()=>setOpen(!open)}><Plus/>Novo cadastro</button></div>{open&&<form className="inline-form" onSubmit={add}><label>{isRecv?'Nome do devedor':'Nome do credor'}<input name="name" required/></label><label>Descrição<input name="description" required/></label><label>Valor<input name="amount" type="number" step=".01" min="0" required/></label><label>Vencimento<input name="due" type="date"/></label>{isRecv&&<label>WhatsApp<input name="phone" placeholder="5511999999999"/></label>}<button className="primary">Salvar</button></form>}<div className="debt-grid">{items.map(x=><div className="debt-card" key={x.id}><div className="debt-top"><div><h3>{x.counterparty_name}</h3><p>{x.description}</p></div><span className={x.status==='overdue'?'danger':'warning'}>{x.status==='paid'?'Quitado':x.next_due_date?new Date(x.next_due_date+'T12:00').toLocaleDateString('pt-BR'):'Sem data'}</span></div><div className="debt-value"><small>Valor restante</small><strong>{money(Number(x.remaining_amount))}</strong></div><div className="card-actions"><button disabled={x.status==='paid'} onClick={()=>settle(x)}><Check/>{isRecv?'Receber':'Pagar'}</button>{isRecv&&x.phone&&<button className="whatsapp" onClick={()=>window.open(`https://wa.me/${x.phone}?text=${encodeURIComponent(`Olá! Passando para lembrar do valor de ${money(Number(x.remaining_amount))} referente a ${x.description}.`)}`)}><Send/>Cobrar</button>}</div></div>)}{!items.length&&<EmptyState text="Nenhum registro cadastrado ainda."/>}</div></>}

function CardsModule({owner,notify}){const[cards,setCards]=useState([]),[open,setOpen]=useState(false);async function load(){const{data}=await supabase.from('cards').select('*').eq('owner_id',owner.id).order('created_at',{ascending:false});setCards(data||[])}useEffect(()=>{load()},[]);async function add(e){e.preventDefault();const f=new FormData(e.currentTarget);const{error}=await supabase.from('cards').insert({owner_id:owner.id,bank:f.get('bank'),name:f.get('name'),credit_limit:Number(f.get('limit')),closing_day:Number(f.get('closing')),due_day:Number(f.get('due')),color:f.get('color')});if(error)return notify('Erro ao cadastrar cartão.');setOpen(false);load();notify('Cartão cadastrado')}return <><div className="page-head"><div><h2>Meus cartões</h2><p>Controle limites e datas de fechamento.</p></div><button className="primary" onClick={()=>setOpen(!open)}><Plus/>Novo cartão</button></div>{open&&<form className="inline-form" onSubmit={add}><label>Banco<input name="bank" required/></label><label>Nome do cartão<input name="name" required/></label><label>Limite<input name="limit" type="number" min="0" step=".01" required/></label><label>Fechamento<input name="closing" type="number" min="1" max="31" required/></label><label>Vencimento<input name="due" type="number" min="1" max="31" required/></label><label>Cor<input name="color" type="color" defaultValue="#6445ed"/></label><button className="primary">Salvar cartão</button></form>}<div className="cards-grid">{cards.map(c=><div className="credit-card" style={{background:`linear-gradient(135deg,${c.color},#071c3a)`}} key={c.id}><CreditCard/><small>{c.bank}</small><h3>{c.name}</h3><strong>Limite {money(Number(c.credit_limit))}</strong><span>Fecha dia {c.closing_day} · vence dia {c.due_day}</span></div>)}{!cards.length&&<EmptyState text="Nenhum cartão cadastrado."/>}</div></>}

function CalendarModule({tx}){const days=Array.from({length:31},(_,i)=>i+1);return <div className="page-panel"><div className="page-head"><div><h2>Calendário financeiro</h2><p>Julho de 2026</p></div></div><div className="calendar-grid">{days.map(d=><div className="calendar-day" key={d}><b>{d}</b>{tx.filter(x=>parseInt(x.date)===d).map(x=><span className={x.type} key={x.id}>{x.name}</span>)}</div>)}</div></div>}
function ReportsModule({tx}){const inc=tx.filter(x=>x.type==='in').reduce((a,x)=>a+x.value,0),out=tx.filter(x=>x.type==='out').reduce((a,x)=>a+x.value,0);function csv(){const body=['Nome,Categoria,Data,Tipo,Valor',...tx.map(x=>`"${x.name}","${x.cat}","${x.date}",${x.type},${x.value}`)].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([body],{type:'text/csv'}));a.download='finance-hub.csv';a.click();URL.revokeObjectURL(a.href)}return <div className="page-panel"><div className="page-head"><div><h2>Relatórios</h2><p>Resumo baseado nas movimentações reais.</p></div><button className="primary" onClick={csv}><Download/>Exportar CSV</button></div><div className="report-grid"><div><span>Receitas</span><strong className="pos">{money(inc)}</strong></div><div><span>Despesas</span><strong className="neg">{money(out)}</strong></div><div><span>Resultado</span><strong>{money(inc-out)}</strong></div><div><span>Lançamentos</span><strong>{tx.length}</strong></div></div><Transactions rows={tx} open={()=>{}}/></div>}
function SettingsModule({owner,dark,setDark,notify}){const[name,setName]=useState(owner.name);async function save(e){e.preventDefault();const{error}=await supabase.from('owners').update({name,updated_at:new Date().toISOString()}).eq('id',owner.id);notify(error?'Erro ao salvar perfil.':'Perfil atualizado. Recarregue para ver o novo nome.')}return <div className="settings-panel"><h2>Configurações</h2><form onSubmit={save}><label>Nome do proprietário<input value={name} onChange={e=>setName(e.target.value)}/></label><label className="setting-row"><span><strong>Tema escuro</strong><small>Alternar aparência do aplicativo</small></span><input type="checkbox" checked={dark} onChange={e=>setDark(e.target.checked)}/></label><button className="primary">Salvar configurações</button></form></div>}
function EmptyState({text}){return <div className="module-empty"><PackageOpen/><strong>{text}</strong><span>Use o botão de cadastro para começar.</span></div>}
function ModulePage({title,notify}){return <div className="empty-module"><div><PackageOpen/></div><h2>{title}</h2><p>Este módulo já está preparado para receber e organizar seus dados financeiros.</p><div><button className="primary" onClick={()=>notify('Novo cadastro iniciado')}><Plus/>Novo cadastro</button><button onClick={()=>notify('Exportação preparada')}><Download/>Exportar</button></div></div>}
function Modal({title,close,children}){return <div className="modal-bg" onMouseDown={close}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><h2>{title}</h2><p>Preencha os dados abaixo.</p></div><button onClick={close}><X/></button></div>{children}</div></div>}

createRoot(document.getElementById('root')).render(<AuthGate/>);
